#include "terminal/editor.h"
#include <QDir>
#include <QFile>
#include <QTemporaryDir>
#include <QtTest>

using namespace ltree;
class TerminalEditorTests : public QObject {
    Q_OBJECT
    QTemporaryDir home_;
    QByteArray homeBefore_, visualBefore_, editorBefore_, pathBefore_;
    QString executable_;
    void write(const QString &path, const QByteArray &data, bool executable = false) {
        QFile file(path);QVERIFY(file.open(QIODevice::WriteOnly));QCOMPARE(file.write(data),qint64(data.size()));file.close();
        if (executable) QVERIFY(file.setPermissions(QFile::ReadOwner | QFile::WriteOwner | QFile::ExeOwner));
    }
private slots:
    void initTestCase() {
        QVERIFY(home_.isValid());homeBefore_=qgetenv("HOME");visualBefore_=qgetenv("VISUAL");editorBefore_=qgetenv("EDITOR");pathBefore_=qgetenv("PATH");
        qputenv("HOME",home_.path().toUtf8());executable_=home_.filePath("my editor");write(executable_,"#!/bin/sh\nexit 0\n",true);
    }
    void init() { QFile::remove(home_.filePath(".selected_editor"));qunsetenv("VISUAL");qunsetenv("EDITOR");qputenv("PATH",home_.path().toUtf8()); }
    void selectedEditorOverridesEnvironment() {
        write(home_.filePath(".selected_editor"),"# Generated by select-editor\nSELECTED_EDITOR=\""+executable_.toUtf8()+"\"\n");
        qputenv("VISUAL","missing-gui");qputenv("EDITOR","missing-editor");QString error;
        QCOMPARE(terminalEditorCommand(&error),QStringList{executable_});QVERIFY(error.isEmpty());
    }
    void selectedAssignmentAndArguments() {
        write(home_.filePath(".selected_editor"),"export SELECTED_EDITOR='\""+executable_.toUtf8()+"\" --wait' # selected\n");
        QCOMPARE(terminalEditorCommand(),(QStringList{executable_,"--wait"}));
    }
    void visualAndEditorArguments() {
        qputenv("EDITOR",("\""+executable_+"\" --editor").toUtf8());QCOMPARE(terminalEditorCommand(),(QStringList{executable_,"--editor"}));
        qputenv("VISUAL",("\""+executable_+"\" --visual \"two words\"").toUtf8());QCOMPARE(terminalEditorCommand(),(QStringList{executable_,"--visual","two words"}));
    }
    void systemDefaultAndMissingEditor() {
        write(home_.filePath("editor"),"#!/bin/sh\nexit 0\n",true);QCOMPARE(terminalEditorCommand(),QStringList{home_.filePath("editor")});
        QFile::remove(home_.filePath("editor"));QString error;QVERIFY(terminalEditorCommand(&error).isEmpty());QVERIFY(error.startsWith("No editor found"));
    }
    void unavailableSelectionReportsError() {
        write(home_.filePath(".selected_editor"),"SELECTED_EDITOR=missing-selected\n");qputenv("EDITOR",executable_.toUtf8());QString error;
        QVERIFY(terminalEditorCommand(&error).isEmpty());QVERIFY(error.contains("missing-selected"));
    }
    void settingsAreNotExecuted() {
        const QString marker=home_.filePath("injected");
        write(home_.filePath(".selected_editor"),"touch "+marker.toUtf8()+"\nSELECTED_EDITOR='"+executable_.toUtf8()+"'\n");
        QCOMPARE(terminalEditorCommand(),QStringList{executable_});QVERIFY(!QFile::exists(marker));
        write(home_.filePath(".selected_editor"),"SELECTED_EDITOR='"+executable_.toUtf8()+"'; touch "+marker.toUtf8()+"\n");QString error;
        QVERIFY(terminalEditorCommand(&error).isEmpty());QVERIFY(error.startsWith("Invalid SELECTED_EDITOR"));QVERIFY(!QFile::exists(marker));
    }
    void binaryDetection_data() {
        QTest::addColumn<QByteArray>("data");QTest::addColumn<bool>("binary");
        QTest::newRow("empty") << QByteArray() << false;
        QTest::newRow("utf8") << QString::fromUtf8("Texto con acentos: canción\n\tOtra línea\r\n").toUtf8() << false;
        QTest::newRow("latin1") << QByteArray::fromHex("63616e6369f36e0a") << false;
        QTest::newRow("utf16le") << QByteArray::fromHex("fffe54006500780074006f000a00") << false;
        QTest::newRow("utf16be") << QByteArray::fromHex("feff0054006500780074006f000a") << false;
        QTest::newRow("utf32le") << QByteArray::fromHex("fffe000054000000650000000a000000") << false;
        QTest::newRow("utf32be") << QByteArray::fromHex("0000feff00000054000000650000000a") << false;
        QTest::newRow("nul") << QByteArray("abc\0def", 7) << true;
        QTest::newRow("binary-without-nul") << QByteArray::fromHex("010203414243") << true;
        QTest::newRow("elf") << QByteArray::fromHex("7f454c4602010100") << true;
        QTest::newRow("zip") << QByteArray::fromHex("504b0304140000000800") << true;
        QTest::newRow("unicode-nul") << QByteArray::fromHex("fffe610000006200") << true;
    }
    void binaryDetection() { QFETCH(QByteArray,data);QFETCH(bool,binary);QCOMPARE(terminalBinaryData(data),binary); }
    void cleanupTestCase() {
        for(const auto &entry:{qMakePair("HOME",homeBefore_),qMakePair("VISUAL",visualBefore_),qMakePair("EDITOR",editorBefore_),qMakePair("PATH",pathBefore_)}) {
            if(entry.second.isNull())qunsetenv(entry.first);else qputenv(entry.first,entry.second);
        }
    }
};
QTEST_GUILESS_MAIN(TerminalEditorTests)
#include "test_terminal_editor.moc"
